// Generated by LiveScript 1.2.0
(function(){
  var matcher, fixtures, Matcher, Book, createBook;
  require('../../test_setup');
  matcher = require('../../../index');
  fixtures = require('../../fixtures');
  Matcher = matcher.accessRequest.SubjectMatcher;
  Book = fixtures.book;
  matcher = function(req){
    return new Matcher(req);
  };
  createBook = function(title){
    return new Book({
      title: title
    });
  };
  describe('SubjectMatcher', function(){
    var subjectMatcher, book, bookTitle, requests;
    requests = {};
    before(function(){
      book = createBook('the return of the jedi');
      return requests.book = {
        subject: book
      };
    });
    describe('create', function(){
      beforeEach(function(){
        return subjectMatcher = matcher(requests.book);
      });
      return specify('must have admin access request', function(){
        return subjectMatcher.accessRequest.should.eql(requests.book);
      });
    });
    return describe('match', function(){
      beforeEach(function(){
        return subjectMatcher = matcher(requests.book);
      });
      specify('should match book: the return of the jedi', function(){
        return subjectMatcher.match({
          title: book.title
        }).should.be['true'];
      });
      specify('should NOT match book: the return to oz', function(){
        return subjectMatcher.match({
          title: 'the return to oz'
        }).should.be['false'];
      });
      return specify('should match on no argument', function(){
        return subjectMatcher.match().should.be['true'];
      });
    });
  });
}).call(this);
